default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
        exclude: ^data/raw_data/merge_data\.py$
      - id: check-builtin-literals
        exclude: ^data/raw_data/merge_data\.py$
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude: ^data/raw_data/merge_data\.py$
      - id: end-of-file-fixer
        exclude: ^data/raw_data/merge_data\.py$
      - id: mixed-line-ending
        exclude: ^data/raw_data/merge_data\.py$
      - id: debug-statements
        exclude: ^data/raw_data/merge_data\.py$
  - repo: https://github.com/myint/autoflake
    rev: "v2.3.1"
    hooks:
      - id: autoflake
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
          ]
        exclude: ^data/raw_data/merge_data\.py$
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: ^data/raw_data/merge_data\.py$
  - repo: https://github.com/ikamensh/flynt
    rev: "1.0.4"
    hooks:
      - id: flynt
        exclude: ^data/raw_data/merge_data\.py$
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort
        args: [--all, --in-place]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black # black should always go after any other autoformatters
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--target-version=py313"]
        language_version: python3.13
        exclude: ^data/raw_data/merge_data\.py$
