default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^audio_files/
      - id: mixed-line-ending
        exclude: ^audio_files/
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade # Must go before autoflake, it may change some dependencies
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--keep-runtime-typing]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.13.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.0"]
  - repo: https://github.com/myint/autoflake
    rev: "v2.0.2"
    hooks:
      - id: autoflake
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
          ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/ikamensh/flynt
    rev: "0.77"
    hooks:
      - id: flynt
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.22.4
    hooks:
      - id: toml-sort
        args: [--all, --in-place]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black # black should always go after any other autoformatters
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--target-version=py311"]
        language_version: python3.13
  # BEGIN LINTERS
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          - --config=pyproject.toml
        additional_dependencies:
          - .[toml]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
        language_version: python3.13
        additional_dependencies:
          - flake8-no-pep420~=2.3
          - flake8-walrus~=1.2
          - flake8-tidy-imports~=4.8
          - flake8-bugbear~=22.9
          - flake8-print~=5.0
