name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install mypy black flake8
          uv pip install -e .
      - name: Run pre-commit checks
        id: precommit
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install pre-commit
          pre-commit run --all-files
        continue-on-error: true
      - name: Run mypy (standalone)
        id: mypy
        run: mypy .
        continue-on-error: true
      - name: Fail if pre-commit or mypy failed
        if: steps.precommit.outcome == 'failure' || steps.mypy.outcome == 'failure'
        run: exit 1
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install -e .
          uv pip install pytest
      - name: Run tests
        run: pytest
